name: Dependency Dispatch

on:
  push:
    branches: [ main, master ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:

  dispatch:
    strategy:
      matrix:
        repo: ["aweps/demo","slaystack/mono"]

    name: Dispatch
    runs-on: ubuntu-latest
    steps:

     - name: Repository Dispatch
       uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 #v2.1.1
       with:
         token: ${{ secrets.PA_TOKEN }}
         repository: ${{ matrix.repo }}
         event-type: dependency_update
         client-payload: '{ "github": ${{ tojson(github) }}}'


